apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rdaszh77k-go 
  janus-idp.io/tekton: rdaszh77k-go
  backstage.io/kubernetes-id: rdaszh77k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rdaszh77k-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml